version: '3.8'

volumes:
  postgres_data:
  static_volume:

networks:
  nginx_network:
    driver: bridge
  postgres_network:
    driver: bridge

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nginx
    ports:
      - 8000:80
    volumes:
      - static_volume:/web/static/
    depends_on:
      - web
    networks:
      - nginx_network

  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    working_dir: /project
    command: "bash ./scripts/web_start.prod.sh"
    volumes:
      - static_volume:/project/src/staticfiles
    networks:
      - postgres_network
      - nginx_network
    expose:
      - "8000"
    env_file:
      - .env.prod
    depends_on:
      - postgres

  postgres:
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - postgres_network
    env_file:
      - .env.prod

  redis:
    image: redis

  celery:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    working_dir: /project
    command: "bash ./scripts/celery_start.dev.sh -t worker"
    env_file:
      - .env.prod
    depends_on:
      - postgres
      - redis
