version: '3.8'

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge


services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: "bash /project/scripts/web_start.dev.sh"
    volumes:
      - ./src:/project/src
    networks:
      - postgres_network
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - postgres

  postgres:
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - postgres_network
    env_file:
      - .env.dev

  redis:
    image: redis

  celery:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    working_dir: /project
    command: "bash ./scripts/celery_start.dev.sh -t worker"
    env_file:
      - .env.dev
    volumes:
      - ./src:/project/src
    depends_on:
      - postgres
      - redis
