version: '3.8'

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge


services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: ['bash', '/usr/src/project/scripts/web_start.dev.sh']
    volumes:
      - ./src:/usr/src/project/src/
      - ./scripts:/usr/src/project/scripts/
    networks:
      - postgres_network
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - postgres_network
    environment:
      - POSTGRES_DB=postgres_dev
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=admin_password

  redis:
    image: redis

  celery:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: ['bash', '/usr/src/project/scripts/celery_start.dev.sh', '-t worker']
    env_file:
      - .env.dev
    volumes:
      - .:/usr/src/project
    depends_on:
      - postgres
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: ['bash', '/usr/src/project/scripts/celery_start.dev.sh', '-t beat']
    env_file:
      - .env.dev
    volumes:
      - .:/usr/src/project
    depends_on:
      - postgres
      - redis
